using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GitCommitsAnalysis.Interfaces;
using GitCommitsAnalysis.Model;

namespace GitCommitsAnalysis.Reporting
{
    public class HTMLReport : BaseReport, IReport
    {
        public HTMLReport(ISystemIO systemIO, string reportFilename, int numberOfFilesToList) : base(systemIO, reportFilename, numberOfFilesToList)
        {
        }

        public void Generate(
            Dictionary<string, FileStat> fileCommits,
            Dictionary<string, FileStat> userfileCommits,
            Dictionary<string, FileStat> folderCommits,
            Dictionary<DateTime, int> commitsEachDay,
            Dictionary<DateTime, int> linesOfCodeAddedEachDay,
            Dictionary<DateTime, int> linesOfCodeDeletedEachDay
            )
        {
            Console.WriteLine("Generating HTML report...");
            if (fileCommits == null) throw new ArgumentException("Parameter fileCommits is null.", nameof(fileCommits));
            if (userfileCommits == null) throw new ArgumentException("Parameter userfileCommits is null.", nameof(userfileCommits));
            if (folderCommits == null) throw new ArgumentException("Parameter folderCommits is null.", nameof(folderCommits));
            if (commitsEachDay == null) throw new ArgumentException("Parameter commitsEachDay is null.", nameof(commitsEachDay));
            if (linesOfCodeAddedEachDay == null) throw new ArgumentException("Parameter linesOfCodeAddedEachDay is null.", nameof(linesOfCodeAddedEachDay));
            if (linesOfCodeDeletedEachDay == null) throw new ArgumentException("Parameter linesOfCodeDeletedEachDay is null.", nameof(linesOfCodeDeletedEachDay));
            this.FileCommitsList = fileCommits.Values.OrderByDescending(fc => fc.CommitCount).ThenBy(fc => fc.Filename);
            this.UserfileCommitsList = userfileCommits.Values.OrderByDescending(fc => fc.CommitCount).ThenBy(fc => fc.Filename).ThenBy(fc => fc.Username);
            var key = 1;
            foreach (var username in userfileCommits.Values.Select(fc => fc.Username).Distinct().OrderBy(un => un))
            {
                UserNameKey.Add(username, key++);
            };
            this.FolderCommits = folderCommits;
            this.FolderCommitsList = folderCommits.Values.OrderByDescending(fc => fc.CommitCount);

            StringBuilder sb = new StringBuilder();
            AddHeader(sb);
            AddNavTabs(sb);
            sb.AppendLine("<div class=\"tab-content\">");
            sb.AppendLine("<div role=\"tabpanel\" class=\"tab-pane active\" id=\"commitsForEachSubfolder\">");
            AddSectionCommitsForEachMonth(sb);
            sb.Append($"<h2 id=\"mostChangedFiles\">Top {NumberOfFilesToList} most changed files</h2>");
            var sectionCounter = 1;
            foreach (var fileChange in FileCommitsList.Take(NumberOfFilesToList))
            {
                AddSectionCommitsForEachFile(sb, fileChange, sectionCounter++);
            }
            sb.AppendLine("</div>");
            sb.AppendLine("<div role=\"tabpanel\" class=\"tab-pane\" id=\"activityEachDay\">");
            AddSectionCommitsForEachDay(sb, commitsEachDay);
            AddSectionLinesChangedEachDay(sb, linesOfCodeAddedEachDay, linesOfCodeDeletedEachDay);
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");
            AddFooter(sb);

            SystemIO.WriteAllText($"{ReportFilename}.html", sb.ToString());
        }

        private void AddHeader(StringBuilder sb)
        {
            sb.AppendLine("<html><head>");
            sb.AppendLine("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" integrity=\"sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu\" crossorigin=\"anonymous\">");
            sb.AppendLine("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>");
            sb.AppendLine("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\" integrity=\"sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd\" crossorigin=\"anonymous\"></script>");
            sb.AppendLine("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>");
            sb.AppendLine("<style>");
            sb.AppendLine("body {");
            sb.AppendLine("   color: black;");
            sb.AppendLine("}");
            sb.AppendLine("</style>");
            sb.AppendLine("</head>");
            sb.AppendLine("<body>");
            sb.AppendLine("<div class=\"container\">");
            sb.AppendLine("<h1 id=\"GitCommitsAnalysis\">GitCommitsAnalysis</h1>");
        }

        private void AddFooter(StringBuilder sb)
        {
            sb.AppendLine("<div class=\"row\">This report was generated by <a href=\"https://github.com/CoderAllan/GitCommitsAnalysis\">GitCommitsAnalysis</a>.</div>");
            sb.AppendLine("</div>");

            sb.AppendLine("</body>");
            sb.AppendLine("</html>");
        }

        private void AddNavTabs(StringBuilder sb)
        {
            sb.AppendLine("<script type=\"javascript\">");
            sb.AppendLine("$('#tabs a[href=\"#commitsForEachSubfolder\"]').click(function (e) { e.preventDefault() $(this).tab('show')})");
            sb.AppendLine("$('#tabs a[href=\"#activityEachDay\"]').click(function (e) { e.preventDefault() $(this).tab('show')})");
            sb.AppendLine("</script>");
            sb.AppendLine("<ul class=\"nav nav-tabs\" role=\"tablist\" id=\"tabs\">");
            sb.AppendLine("<li role=\"presentation\" class=\"active\"><a href=\"#commitsForEachSubfolder\" aria-controls=\"home\" role=\"tab\" data-toggle=\"tab\">Commits for each subfolder</a></li>");
            sb.AppendLine("<li role=\"presentation\"><a href=\"#activityEachDay\" aria-controls=\"activityEachDay\" role=\"tab\" data-toggle=\"tab\">Activity each date</a></li>");
            sb.AppendLine("</ul>");
        }

        private void AddPieChartJavascript(StringBuilder sb)
        {
            sb.AppendLine("<script type=\"text/javascript\">");
            sb.AppendLine("google.charts.load('current', { 'packages':['corechart']});");
            sb.AppendLine("google.charts.setOnLoadCallback(drawChart);");
            sb.AppendLine("function drawChart() {");
            sb.AppendLine("   var data = google.visualization.arrayToDataTable([['Folder', 'Commits'], ");
            foreach (var folder in FolderCommitsList.Take(25))
            {
                sb.AppendLine($"      ['{folder.Filename}', {folder.CommitCount}],");
            }
            sb.AppendLine("   ]);");
            sb.AppendLine("   var options = { title: 'Commits for each subfolder' }; ");
            sb.AppendLine("   var chart = new google.visualization.PieChart(document.getElementById('piechart'));");
            sb.AppendLine("   chart.draw(data, options);");
            sb.AppendLine("}");
            sb.AppendLine("</script>");
        }

        private void AddSectionCommitsForEachMonth(StringBuilder sb)
        {
            var totalCommits = FileCommitsList.Sum(fc => fc.CommitCount);
            sb.AppendLine("<div class=\"row\">");
            sb.AppendLine("<div class=\"col-md-6\">");
            sb.AppendLine("<h2>Commits for each subfolder</h2>");
            sb.AppendLine("<table class=\"table pull-left\" style=\"width: 500px\">");
            sb.AppendLine("<tr><th class=\"text-right\">Folder</th><th class=\"text-right\">Commits</th></tr>");
            foreach (var folder in FolderCommitsList.Take(25))
            {
                var changeCount = string.Format("{0,5}", FolderCommits[folder.Filename].CommitCount);
                var percentage = string.Format("{0,5:#0.0}", ((double)FolderCommits[folder.Filename].CommitCount / (double)totalCommits) * 100);
                sb.AppendLine($"<tr><td class=\"text-right\">{folder.Filename}</td><td class=\"text-right\">{changeCount} ({percentage}%)</td></tr>");
            }
            var total = string.Format("{0,5}", totalCommits);
            sb.AppendLine($"<tr><td class=\"text-right\">Total number of Commits analyzed</td><td class=\"text-right\">{total} ({string.Format("{0,5:##0.0}", 100)}%)</td></tr>");
            sb.AppendLine("</table>\n");
            sb.AppendLine("</div>");
            sb.AppendLine("<div class=\"col-md-6\">");
            AddPieChartJavascript(sb);
            sb.AppendLine("<div id=\"piechart\" style=\"width: 900px; height: 500px; \"></div>");
            sb.AppendLine("</div></div>");
        }

        private void AddcommitsEachDayChartJavascript(StringBuilder sb, Dictionary<DateTime, int> commitsEachDay)
        {
            sb.AppendLine("<script type=\"text/javascript\">");
            sb.AppendLine("google.charts.load('current', { 'packages':['corechart']});");
            sb.AppendLine("google.charts.setOnLoadCallback(drawChart);");
            sb.AppendLine("function drawChart() {");
            sb.AppendLine($"var data = new google.visualization.DataTable();");
            sb.AppendLine($"data.addColumn('date', 'Date');");
            sb.AppendLine($"data.addColumn('number', 'Commits');");
            sb.AppendLine($"data.addColumn({{ type: 'string', role: 'tooltip'}});");
            sb.AppendLine($"data.addRows([");
            var dateOfFirstCommit = commitsEachDay.Keys.OrderBy(date => date).First();
            for (var date = dateOfFirstCommit; date <= DateTime.Now; date = date.AddDays(1))
            {
                var numberOfCommits = commitsEachDay.ContainsKey(date) ? commitsEachDay[date] : 0;
                sb.AppendLine($"      [new Date('{date.ToString("yyyy-MM-dd")}'), {numberOfCommits}, '{date.ToString("yyyy-MM-dd")}, {numberOfCommits}'],");
            }
            sb.AppendLine("   ]);");
            sb.AppendLine("   var options = { width: 1200, height: 500, legend: 'none', hAxis: { title: 'Date'}, vAxis: { title: 'Commits' } }; ");
            sb.AppendLine("   var chart = new google.visualization.LineChart(document.getElementById('commitsEachDayChart'));");
            sb.AppendLine("   chart.draw(data, options);");
            sb.AppendLine("}");
            sb.AppendLine("</script>");
        }

        private void AddSectionCommitsForEachDay(StringBuilder sb, Dictionary<DateTime, int> commitsEachDay)
        {
            // var totalCommits = FileCommitsList.Sum(fc => fc.CommitCount);
            sb.AppendLine("<div class=\"row\">");
            sb.AppendLine("<div class=\"col\">");
            sb.AppendLine("<h2>Commits for each day</h2>");
            sb.AppendLine("");
            AddcommitsEachDayChartJavascript(sb, commitsEachDay);
            sb.AppendLine("<div id=\"commitsEachDayChart\"></div>");
            sb.AppendLine("</div></div>");
        }

        private void AddLinesChangedEachDayChartJavascript(StringBuilder sb, Dictionary<DateTime, int> linesOfCodeAddedEachDay, Dictionary<DateTime, int> linesOfCodeDeletedEachDay)
        {
            sb.AppendLine("<script type=\"text/javascript\">");
            sb.AppendLine("google.charts.load('current', { 'packages':['corechart']});");
            sb.AppendLine("google.charts.setOnLoadCallback(drawChart);");
            sb.AppendLine("function drawChart() {");
            sb.AppendLine($"var data = new google.visualization.DataTable();");
            sb.AppendLine($"data.addColumn('date', 'Date');");
            sb.AppendLine($"data.addColumn('number', 'Lines added');");
            sb.AppendLine($"data.addColumn('number', 'Lines deleted');");
            sb.AppendLine($"data.addColumn({{ type: 'string', role: 'tooltip'}});");
            sb.AppendLine($"data.addRows([");
            var dateOfFirstChange = linesOfCodeAddedEachDay.Keys.OrderBy(date => date).First();
            for (var date = dateOfFirstChange; date <= DateTime.Now; date = date.AddDays(1))
            {
                var numberOfLinesAdded = linesOfCodeAddedEachDay.ContainsKey(date) ? linesOfCodeAddedEachDay[date] : 0;
                var numberOfLinesDeleted = linesOfCodeDeletedEachDay.ContainsKey(date) ? linesOfCodeDeletedEachDay[date] : 0;
                sb.AppendLine($"      [new Date('{date.ToString("yyyy-MM-dd")}'), {numberOfLinesAdded}, {numberOfLinesDeleted}, '{date.ToString("yyyy-MM-dd")}, +{numberOfLinesAdded}, -{numberOfLinesDeleted}'],");
            }
            sb.AppendLine("   ]);");
            sb.AppendLine("   var options = { width: 1200, height: 500, hAxis: { title: 'Date'}, vAxis: { title: 'Lines added/deleted' } }; ");
            sb.AppendLine("   var chart = new google.visualization.LineChart(document.getElementById('linesChangedEachDayChart'));");
            sb.AppendLine("   chart.draw(data, options);");
            sb.AppendLine("}");
            sb.AppendLine("</script>");
        }

        private void AddSectionLinesChangedEachDay(StringBuilder sb, Dictionary<DateTime, int> linesOfCodeAddedEachDay, Dictionary<DateTime, int> linesOfCodeDeletedEachDay)
        {
            sb.AppendLine("<div class=\"row\">");
            sb.AppendLine("<div class=\"col\">");
            sb.AppendLine("<h2>Lines changed each day</h2>");
            sb.AppendLine("");
            AddLinesChangedEachDayChartJavascript(sb, linesOfCodeAddedEachDay, linesOfCodeDeletedEachDay);
            sb.AppendLine("<div id=\"linesChangedEachDayChart\"></div>");
            sb.AppendLine("</div></div>");
        }

        private void AddSectionCommitsForEachFile(StringBuilder sb, FileStat fileChange, int sectionCounter)
        {
            var linesOfCode = fileChange.LinesOfCode > 0 ? fileChange.LinesOfCode.ToString() : "N/A";
            var cyclomaticComplexity = fileChange.CyclomaticComplexity > 0 ? fileChange.CyclomaticComplexity.ToString() : "N/A";
            sb.AppendLine("<div class=\"row\"><div class=\"col-md-6\">");
            sb.AppendLine($"<h3>{fileChange.Filename}</h3>");
            sb.AppendLine("<table class=\"table pull-left\" style=\"width: 500px\">");
            sb.AppendLine($"<tr><td class=\"text-right\">Commits</td><td>{fileChange.CommitCount}</td></tr>");
            sb.AppendLine($"<tr><td class=\"text-right\">Lines of code</td><td>{linesOfCode}</td></tr>");
            sb.AppendLine($"<tr><td class=\"text-right\">Cyclomatic Complexity</td><td>{cyclomaticComplexity}</td></tr>");
            sb.AppendLine("</table>");
            sb.AppendLine("</div>");
            sb.AppendLine("<div class=\"col-md-6\">");
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");

            sb.AppendLine("<div class=\"row\"><div class=\"col-md-6\">");
            sb.AppendLine("<table class=\"table pull-left\" style=\"width: 500px\">");
            sb.AppendLine($"<tr><th>Name</th><th>Commits</th><th>Percentage</th><th>Latest commit</th></tr>");
            var commitDates = new List<ScatterPoint>();
            foreach (var userfileChange in UserfileCommitsList.Where(ufc => ufc.Filename == fileChange.Filename))
            {
                var username = string.Format("{0,20}", userfileChange.Username);
                var changeCount = string.Format("{0,3}", userfileChange.CommitCount);
                var percentage = string.Format("{0,5:#0.00}", ((double)userfileChange.CommitCount / (double)fileChange.CommitCount) * 100);
                var latestCommit = GenerateScatterPlotData(commitDates, userfileChange);
                sb.AppendLine($"<tr><td class=\"text-right\">{username}</td><td>{changeCount}</td><td>{percentage}%</td><td>{latestCommit}</td></tr>");
            }

            sb.AppendLine("</table>");
            sb.AppendLine("</div>");

            sb.AppendLine("<div class=\"col-md-6\">");
            AddScatterplotJavascript(sb, commitDates, sectionCounter);
            sb.AppendLine($"    <div id=\"scatterChart{sectionCounter}\" style=\"width: 900px; height: 300px; \"></div>");
            sb.AppendLine("</div>");
            sb.AppendLine("</div>");
        }

        private string GenerateScatterPlotData(List<ScatterPoint> commitDates, FileStat fileStat)
        {
            var commitDatesOrdered = fileStat.CommitDates.OrderBy(date => date);
            foreach (var commitDate in commitDatesOrdered)
            {
                var date = $"new Date('{commitDate.ToString("yyyy-MM-dd")}')";
                var userId = UserNameKey[fileStat.Username];
                if (!commitDates.Any(cd => cd.Date == date && cd.UserId == userId)) // Only add a point for each user for each date
                {
                    commitDates.Add(new ScatterPoint
                    {
                        Date = date,
                        UserId = userId,
                        ToolTip = $"'{commitDate.ToString("yyyy-MM-dd")}, {fileStat.Username}'"
                    });
                }
            }
            var latestCommitDate = commitDatesOrdered.Last();
            return latestCommitDate.ToString("yyyy-MM-dd");
        }

        private static void AddScatterplotJavascript(StringBuilder sb, List<ScatterPoint> commitDates, int sectionCounter)
        {
            var commitDatesString = string.Join(",", commitDates.Select(sp => sp.ToString()).OrderBy(sp => sp));

            sb.AppendLine("<script type=\"text/javascript\">");
            sb.AppendLine("google.charts.load('current', { 'packages':['corechart'] });");
            sb.AppendLine($"google.charts.setOnLoadCallback(drawChart{sectionCounter});");
            sb.AppendLine($"function drawChart{sectionCounter}() {{");
            sb.AppendLine($"var data{sectionCounter} = new google.visualization.DataTable();");
            sb.AppendLine($"data{sectionCounter}.addColumn('date', 'Date');");
            sb.AppendLine($"data{sectionCounter}.addColumn('number', 'UserId');");
            sb.AppendLine($"data{sectionCounter}.addColumn({{ type: 'string', role: 'tooltip'}});");
            sb.AppendLine($"data{sectionCounter}.addRows([");
            sb.AppendLine(commitDatesString);
            sb.AppendLine("]);");
            sb.AppendLine("var options = { title: 'User commits for each date', legend: 'none' };");
            sb.AppendLine($"var chart = new google.visualization.ScatterChart(document.getElementById('scatterChart{sectionCounter}'));");
            sb.AppendLine($"chart.draw(data{sectionCounter}, options);");
            sb.AppendLine("}");
            sb.AppendLine("</script>");
        }

    }
}
